import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('iris_data.csv')
plt.xlabel('SepalLengthCm')
plt.ylabel('SepalWidthCm')
plt.plot(df['SepalLengthCm'],df['SepalWidthCm'])
plt.show()
df = pd.read_csv('iris_data.csv')
plt.xlabel('SepalLengthCm')
plt.ylabel('PetalLengthCm')
plt.plot(df['SepalLengthCm'],df['PetalLengthCm'])
plt.show()
df = pd.read_csv('iris_data.csv')
plt.xlabel('SepalLengthCm')
plt.ylabel('PetalWidthCm')
plt.plot(df['SepalLengthCm'],df['PetalWidthCm'])
plt.show()
df = pd.read_csv('iris_data.csv')
plt.xlabel('PetalLengthCm')
plt.ylabel('PetalWidthCm')
plt.plot(df['PetalLengthCm'],df['PetalWidthCm'])
plt.show()
df = pd.read_csv('iris_data.csv')
plt.xlabel('PetalLengthCm')
plt.ylabel('SepalWidthCm')
plt.plot(df['PetalLengthCm'],df['SepalWidthCm'])
plt.show()
df = pd.read_csv('iris_data.csv')
plt.xlabel('PetalLengthCm')
plt.ylabel('SepalLengthCm')
plt.plot(df['PetalLengthCm'],df['SepalLengthCm'])
plt.show()


